version: '3.8'

services:
  app:
    # Bazowy obraz Debiana - resztę narzędzi wstrzyknie devcontainer.json
    image: mcr.microsoft.com/devcontainers/base:bookworm
    # Usypiamy kontener, by działał w tle i czekał na połączenie z VS Code
    command: sleep infinity
    volumes:
      - .:/workspace:cached
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/vextro_db
    depends_on:
      - db
    networks:
      - vextro-net
    # Konieczne, by pnpm nie wywalał błędów z prawami dostępu
    user: node

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: vextro_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      # Inna nazwa wolumenu, żeby dev-baza nie gryzła się z danymi z kontenera produkcyjnego
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - vextro-net

volumes:
  postgres_data_dev:

networks:
  vextro-net:
    driver: bridge